/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmMDIprincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    private String usuarioCargo;
    public static String usuarioApellidoNombre;
    public static String usuarioId;
    public static String proyectoId;
    private static final Font FUENTE_DEFAULT = new Font("Droid Sans", Font.PLAIN, 12);
     public String Nombre;
    public String Apellido;
    public String Cargo;
  
    //El constructor recibe los datos de jefe de proyecto y nombres del usuario
    //para que puedan ser trabajados por todo el sistema.
    public FrmMDIprincipal(String xUsuarioCargo, String xUsuarioNombreApellido, 
            String xUsuarioId) {
       
        initComponents();
        if(usuarioCargo=="Administrador"){
        AbrirFrmProyectoUsuario();
        }
        else{AbrirFrmProyectoJefe();}
        
        FechaActual();
        usuarioCargo = xUsuarioCargo;
        usuarioApellidoNombre = xUsuarioNombreApellido;
        usuarioId = xUsuarioId;
        System.out.println(usuarioCargo);
        lblusuario.setFont(FUENTE_DEFAULT);
        lblusuario.setText(usuarioApellidoNombre);  
      
    }
     private void FechaActual()
    {
        Date date = new Date();
        String format = new String("dd/MM/yyyy");
        SimpleDateFormat formato = new SimpleDateFormat(format);
        lblfecha.setText(formato.format(date));
    }
     
    public void ObtenerDatos(){
    String Usuario;
    Usuario= Nombre + "" + Apellido + "" ;
    lblusuario.setText(Usuario);
    }
     public void Salir()
    {
        int resp;
        resp = JOptionPane.showConfirmDialog(null,"Esta seguro de salir del sistema...?","Sistema Kardex",0);
        if(resp == 0)
        {
            System.exit(resp);
        }
    }
   /**
     * Abre la vista principal de proyectos del jefe.
     */
    public void AbrirFrmProyectoJefe() {
        
        int x = (Escritorio.getWidth());
        int y = (Escritorio.getHeight()); 
        FrmProyectoJefe proyectosjefe = new FrmProyectoJefe();
        Escritorio.removeAll();
        Escritorio.updateUI();
        if (proyectosjefe.isShowing()) 
        {
            proyectosjefe.setLocation(x, y);
        } 
        else 
        {
            Escritorio.add(proyectosjefe);
            proyectosjefe.setBounds(0,0,x, y);
            proyectosjefe.FormularioPrincipalJefe(this);
            proyectosjefe.setVisible(true);            
        }
    }
    
     /**
     * Abre la vista principal de proyectos del usuario.
     */
    public void AbrirFrmProyectoUsuario() {
        
        int x = (Escritorio.getWidth());
        int y = (Escritorio.getHeight()); 
        FrmProyectoUsuario proyectosusu = new FrmProyectoUsuario();
        Escritorio.removeAll();
        Escritorio.updateUI();
        if (proyectosusu.isShowing()) 
        {
            proyectosusu.setLocation(x, y);
        } 
        else 
        {
            Escritorio.add(proyectosusu);
            proyectosusu.setBounds(0,0,x, y);
            proyectosusu.FormularioPrincipalUsu(this);
            proyectosusu.setVisible(true);            
        }
    }
    
     /**
     * Abre la vista de nuevo proyecto
     */
    public void AbrirFrmNuevoProyecto() {
        
        int x = (Escritorio.getWidth());
        int y = (Escritorio.getHeight()); 
        FrmNuevoProyecto proyectonuev = new FrmNuevoProyecto();
        Escritorio.removeAll();
        Escritorio.updateUI();
        if (proyectonuev.isShowing()) 
        {
            proyectonuev.setLocation(x, y);
        } 
        else 
        {
            Escritorio.add(proyectonuev);
            proyectonuev.setBounds(0,0,x, y);
            proyectonuev.FormularioNuevoProyecto(this);
            proyectonuev.setVisible(true);            
        }
    }
    
    public FrmMDIprincipal() {
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        pnlBot = new javax.swing.JPanel();
        jlabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        BtnNuevoPry = new javax.swing.JButton();
        BtnPryArchiva = new javax.swing.JButton();
        BtnInformeEstad = new javax.swing.JButton();
        BtnSalir1 = new javax.swing.JButton();
        mbrPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuPry = new javax.swing.JMenu();
        MenuProyectos = new javax.swing.JMenuItem();
        MenuProyectosArchiv = new javax.swing.JMenuItem();
        MenuInformeEstado = new javax.swing.JMenuItem();
        MenuCmb = new javax.swing.JMenu();
        MenuSolicitudCambio = new javax.swing.JMenuItem();
        MenuCambioDeriva = new javax.swing.JMenuItem();
        MenuConfig = new javax.swing.JMenu();
        MenuParticipant = new javax.swing.JMenuItem();
        MenuEntregab = new javax.swing.JMenuItem();
        MenuAyuda = new javax.swing.JMenu();
        MenuCerrarSesion = new javax.swing.JMenu();
        reportUsu = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Gestor de Configuración de Proyectos");

        Escritorio.setLayout(new java.awt.BorderLayout());

        pnlBot.setBackground(new java.awt.Color(255, 255, 255));

        jlabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlabel1.setText("Usuario: ");

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fecha:");

        lblfecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout pnlBotLayout = new javax.swing.GroupLayout(pnlBot);
        pnlBot.setLayout(pnlBotLayout);
        pnlBotLayout.setHorizontalGroup(
            pnlBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jlabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(14, 14, 14)
                .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotLayout.setVerticalGroup(
            pnlBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotLayout.createSequentialGroup()
                .addGroup(pnlBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabel1)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        BtnNuevoPry.setBackground(new java.awt.Color(204, 204, 204));
        BtnNuevoPry.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        BtnNuevoPry.setForeground(new java.awt.Color(0, 153, 153));
        BtnNuevoPry.setText("Nuevo Proyecto");
        BtnNuevoPry.setFocusable(false);
        BtnNuevoPry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnNuevoPry.setMaximumSize(new java.awt.Dimension(57, 49));
        BtnNuevoPry.setMinimumSize(new java.awt.Dimension(57, 49));
        BtnNuevoPry.setPreferredSize(new java.awt.Dimension(57, 49));
        BtnNuevoPry.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnNuevoPry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoPryActionPerformed(evt);
            }
        });

        BtnPryArchiva.setBackground(new java.awt.Color(204, 204, 204));
        BtnPryArchiva.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        BtnPryArchiva.setForeground(new java.awt.Color(0, 153, 153));
        BtnPryArchiva.setText("Proyectos Archivados");
        BtnPryArchiva.setFocusable(false);
        BtnPryArchiva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnPryArchiva.setMaximumSize(new java.awt.Dimension(57, 49));
        BtnPryArchiva.setMinimumSize(new java.awt.Dimension(57, 49));
        BtnPryArchiva.setPreferredSize(new java.awt.Dimension(57, 49));
        BtnPryArchiva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnPryArchiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPryArchivaActionPerformed(evt);
            }
        });

        BtnInformeEstad.setBackground(new java.awt.Color(204, 204, 204));
        BtnInformeEstad.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        BtnInformeEstad.setForeground(new java.awt.Color(0, 153, 153));
        BtnInformeEstad.setText("Informe de Estado");
        BtnInformeEstad.setFocusable(false);
        BtnInformeEstad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnInformeEstad.setMaximumSize(new java.awt.Dimension(57, 49));
        BtnInformeEstad.setMinimumSize(new java.awt.Dimension(57, 49));
        BtnInformeEstad.setPreferredSize(new java.awt.Dimension(57, 49));
        BtnInformeEstad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnInformeEstad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInformeEstadActionPerformed(evt);
            }
        });

        BtnSalir1.setBackground(new java.awt.Color(204, 204, 204));
        BtnSalir1.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        BtnSalir1.setForeground(new java.awt.Color(0, 153, 153));
        BtnSalir1.setText("Salir");
        BtnSalir1.setFocusable(false);
        BtnSalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalir1.setMaximumSize(new java.awt.Dimension(57, 49));
        BtnSalir1.setMinimumSize(new java.awt.Dimension(57, 49));
        BtnSalir1.setPreferredSize(new java.awt.Dimension(57, 49));
        BtnSalir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir1ActionPerformed(evt);
            }
        });

        mbrPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setContentAreaFilled(false);
        jMenu1.setEnabled(false);
        jMenu1.setFocusable(false);
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        jMenu1.setIconTextGap(0);
        mbrPrincipal.add(jMenu1);

        MenuPry.setForeground(new java.awt.Color(0, 153, 153));
        MenuPry.setText("Proyectos");

        MenuProyectos.setForeground(new java.awt.Color(0, 153, 153));
        MenuProyectos.setText("Proyectos");
        MenuProyectos.setName(""); // NOI18N
        MenuProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProyectosActionPerformed(evt);
            }
        });
        MenuPry.add(MenuProyectos);

        MenuProyectosArchiv.setForeground(new java.awt.Color(0, 153, 153));
        MenuProyectosArchiv.setText("Proyectos Archivados");
        MenuProyectosArchiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuProyectosArchivMouseClicked(evt);
            }
        });
        MenuProyectosArchiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuProyectosArchivActionPerformed(evt);
            }
        });
        MenuPry.add(MenuProyectosArchiv);

        MenuInformeEstado.setForeground(new java.awt.Color(0, 102, 102));
        MenuInformeEstado.setText("Informe de Estado");
        MenuInformeEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInformeEstadoActionPerformed(evt);
            }
        });
        MenuPry.add(MenuInformeEstado);

        mbrPrincipal.add(MenuPry);

        MenuCmb.setForeground(new java.awt.Color(0, 153, 153));
        MenuCmb.setText("Cambios");

        MenuSolicitudCambio.setForeground(new java.awt.Color(0, 153, 153));
        MenuSolicitudCambio.setText("Solicitud de Cambios");
        MenuSolicitudCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSolicitudCambioActionPerformed(evt);
            }
        });
        MenuCmb.add(MenuSolicitudCambio);

        MenuCambioDeriva.setForeground(new java.awt.Color(0, 153, 153));
        MenuCambioDeriva.setText("Cambios Derivados");
        MenuCambioDeriva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCambioDerivaActionPerformed(evt);
            }
        });
        MenuCmb.add(MenuCambioDeriva);

        mbrPrincipal.add(MenuCmb);

        MenuConfig.setForeground(new java.awt.Color(0, 153, 153));
        MenuConfig.setText("Configuracion");

        MenuParticipant.setForeground(new java.awt.Color(0, 102, 102));
        MenuParticipant.setText("Participantes");
        MenuParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuParticipantActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuParticipant);

        MenuEntregab.setForeground(new java.awt.Color(0, 102, 102));
        MenuEntregab.setText("Entregables");
        MenuEntregab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEntregabActionPerformed(evt);
            }
        });
        MenuConfig.add(MenuEntregab);

        mbrPrincipal.add(MenuConfig);

        MenuAyuda.setForeground(new java.awt.Color(0, 153, 153));
        MenuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/info.png"))); // NOI18N
        MenuAyuda.setText("Ayuda");
        mbrPrincipal.add(MenuAyuda);

        MenuCerrarSesion.setForeground(new java.awt.Color(0, 153, 153));
        MenuCerrarSesion.setText("Sesion");

        reportUsu.setForeground(new java.awt.Color(0, 102, 102));
        reportUsu.setText("Cerrar Sesion");
        reportUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportUsuActionPerformed(evt);
            }
        });
        MenuCerrarSesion.add(reportUsu);

        MenuSalir.setForeground(new java.awt.Color(0, 153, 153));
        MenuSalir.setText("Salir");
        MenuSalir.setToolTipText("");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        MenuCerrarSesion.add(MenuSalir);

        mbrPrincipal.add(MenuCerrarSesion);

        setJMenuBar(mbrPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnNuevoPry, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnPryArchiva, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInformeEstad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnNuevoPry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(BtnPryArchiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(BtnInformeEstad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(BtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 278, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Escritorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(pnlBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProyectosActionPerformed

    }//GEN-LAST:event_MenuProyectosActionPerformed

    private void MenuProyectosArchivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProyectosArchivMouseClicked

    }//GEN-LAST:event_MenuProyectosArchivMouseClicked

    private void MenuProyectosArchivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuProyectosArchivActionPerformed

    }//GEN-LAST:event_MenuProyectosArchivActionPerformed

    private void MenuInformeEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInformeEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuInformeEstadoActionPerformed

    private void MenuSolicitudCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSolicitudCambioActionPerformed

    }//GEN-LAST:event_MenuSolicitudCambioActionPerformed

    private void MenuCambioDerivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCambioDerivaActionPerformed

    }//GEN-LAST:event_MenuCambioDerivaActionPerformed

    private void MenuParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuParticipantActionPerformed

    }//GEN-LAST:event_MenuParticipantActionPerformed

    private void MenuEntregabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEntregabActionPerformed

    }//GEN-LAST:event_MenuEntregabActionPerformed

    private void reportUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportUsuActionPerformed

    }//GEN-LAST:event_reportUsuActionPerformed

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        Salir();
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void BtnNuevoPryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoPryActionPerformed
        AbrirFrmNuevoProyecto();
    }//GEN-LAST:event_BtnNuevoPryActionPerformed

    private void BtnPryArchivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPryArchivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnPryArchivaActionPerformed

    private void BtnInformeEstadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInformeEstadActionPerformed

    }//GEN-LAST:event_BtnInformeEstadActionPerformed

    private void BtnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir1ActionPerformed
        Salir();
    }//GEN-LAST:event_BtnSalir1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInformeEstad;
    private javax.swing.JButton BtnNuevoPry;
    private javax.swing.JButton BtnPryArchiva;
    private javax.swing.JButton BtnSalir1;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu MenuAyuda;
    private javax.swing.JMenuItem MenuCambioDeriva;
    private javax.swing.JMenu MenuCerrarSesion;
    private javax.swing.JMenu MenuCmb;
    private javax.swing.JMenu MenuConfig;
    private javax.swing.JMenuItem MenuEntregab;
    private javax.swing.JMenuItem MenuInformeEstado;
    private javax.swing.JMenuItem MenuParticipant;
    private javax.swing.JMenuItem MenuProyectos;
    private javax.swing.JMenuItem MenuProyectosArchiv;
    private javax.swing.JMenu MenuPry;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JMenuItem MenuSolicitudCambio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JMenuBar mbrPrincipal;
    private javax.swing.JPanel pnlBot;
    private javax.swing.JMenuItem reportUsu;
    // End of variables declaration//GEN-END:variables
}
